# Generated by Django 5.0.4 on 2024-04-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Dia que a Lead Chegou')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nome da Lead')),
                ('last_name', models.CharField(max_length=255, verbose_name='Sobrenome da Lead')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='Whatsapp (Telefone)')),
                ('first_contact_date', models.DateField(verbose_name='Data Primeiro Contato')),
                ('objective', models.TextField(verbose_name='Objetivo da Lead')),
                ('priority', models.IntegerField(verbose_name='Prioridade')),
            ],
        ),
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
