# Generated by Django 5.0.4 on 2024-04-25 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_delete_leads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Leads',
        ),
    ]
