# Generated by Django 5.0.4 on 2024-04-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_rename_lead_leads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leads',
            new_name='Lead',
        ),
    ]
