# Generated by Django 5.0.4 on 2024-04-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_rename_leads_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome da Lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='Nome da Lead'),
        ),
    ]
