# Generated by Django 5.0.4 on 2024-04-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_city_lead_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_contact_date',
            field=models.DateField(blank=True, verbose_name='Data Primeiro Contato'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
    ]
