# Generated by Django 5.0.4 on 2024-04-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_city_alter_lead_first_contact_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='first_contact_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Primeiro Contato'),
        ),
    ]
