# Generated by Django 5.0.4 on 2024-04-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_lead_first_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='objective',
            field=models.CharField(choices=[('sales', 'Vendas'), ('support', 'Suporte'), ('feedback', 'Feedback'), ('other', 'Outro'), ('Teste', 'Teste')], default='other', max_length=100, verbose_name='Objetivo da Lead'),
        ),
    ]
