# Generated by Django 5.0.4 on 2024-04-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_servicetype_lead_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram'),
        ),
    ]
