# Generated by Django 5.0.4 on 2024-04-30 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_lead_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='objective',
        ),
    ]
