# Generated by Django 5.0.4 on 2024-05-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_lead_return_contac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='return_contac',
            new_name='return_contact',
        ),
    ]
