# Generated by Django 5.0.4 on 2024-05-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_rename_return_contac_lead_return_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Serviço Prestado'),
        ),
    ]
