# Generated by Django 5.0.4 on 2024-05-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_remove_lead_last_name_lead_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='priority',
        ),
    ]
