# Generated by Django 5.0.4 on 2024-05-13 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.priority', verbose_name='Prioridade'),
        ),
    ]
