# Generated by Django 5.0.4 on 2024-05-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_lead_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_info',
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
