# Generated by Django 5.0.4 on 2024-05-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_lead_lead_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_info',
            field=models.TextField(blank=True, max_length=2500, verbose_name='Informações Sobre a Lead'),
        ),
    ]
