# Generated by Django 5.0.4 on 2024-05-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_lead_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='responsavel',
            new_name='responsible',
        ),
    ]
