# Generated by Django 5.0.4 on 2024-05-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_rename_responsavel_lead_responsible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Origem da Lead')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='Origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.origin', verbose_name='Origem da Lead'),
        ),
    ]
