# Generated by Django 5.0.4 on 2024-05-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_origin_lead_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='Origin',
            new_name='origin',
        ),
    ]
