# Generated by Django 5.0.4 on 2024-06-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_alter_followup_notes_alter_followup_planned_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='planned_date',
            new_name='return_contact',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='actual_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='first_contact_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='return_contact',
        ),
        migrations.AddField(
            model_name='followup',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Último Contato'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='notes',
            field=models.TextField(blank=True, default='Sem Nota', max_length=50, verbose_name='Anotações'),
        ),
    ]
