# Generated by Django 5.0.4 on 2024-06-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_remove_lead_first_contact_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='actual_date',
            new_name='last_contact_date',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='planned_date',
            new_name='return_contact',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_contact_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='return_contact',
        ),
    ]
