# Generated by Django 5.0.4 on 2024-06-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_rename_actual_date_followup_last_contact_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Último Contato'),
        ),
        migrations.AddField(
            model_name='lead',
            name='return_contact',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Próximo Contato'),
        ),
    ]
