# Generated by Django 5.0.4 on 2024-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_lead_last_contact_date_lead_return_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='notes',
            field=models.TextField(blank=True, default='Sem Nota', max_length=50, verbose_name='Anotações'),
        ),
    ]
