# Generated by Django 5.0.4 on 2024-06-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_alter_followup_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='last_contact_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='return_contact',
        ),
    ]
