# Generated by Django 5.0.4 on 2024-06-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_phone_number', models.CharField(max_length=15)),
                ('profile_name', models.CharField(max_length=100)),
                ('whatsapp_id', models.CharField(max_length=20)),
                ('message_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('message_text', models.TextField()),
                ('business_phone_number', models.CharField(max_length=15)),
                ('phone_id', models.CharField(max_length=20)),
                ('chat_history', models.TextField()),
                ('state', models.CharField(default='initial', max_length=50)),
                ('thanked', models.BooleanField(default=False)),
                ('service_interest', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_method', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
