# Generated by Django 5.0.4 on 2024-06-15 16:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visualadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_phone_number', models.CharField(max_length=20, unique=True)),
                ('profile_name', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_id', models.CharField(blank=True, max_length=20, null=True)),
                ('message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('message_text', models.TextField()),
                ('business_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_id', models.CharField(blank=True, max_length=20, null=True)),
                ('chat_history', models.TextField(blank=True, null=True)),
                ('contacted', models.BooleanField(default=False)),
                ('service_interest', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_method', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualadmin.chatbotstate')),
            ],
        ),
    ]
