# Generated by Django 5.0.4 on 2024-06-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpmessage',
            name='business_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='wpmessage',
            name='chat_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wpmessage',
            name='message_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wpmessage',
            name='phone_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wpmessage',
            name='profile_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wpmessage',
            name='state',
            field=models.CharField(blank=True, default='initial', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wpmessage',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wpmessage',
            name='whatsapp_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
