# Generated by Django 5.0.4 on 2024-06-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0002_wpmessage_delete_wpmessages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wpmessage',
            old_name='thanked',
            new_name='contacted',
        ),
    ]
