# Generated by Django 5.0.4 on 2024-06-09 21:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0003_rename_thanked_wpmessage_contacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpmessage',
            name='message_timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='wpmessage',
            name='state',
            field=models.CharField(blank=True, default='Initial', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ChatbotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('next_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_states', to='wpmessages.chatbotstate')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=100)),
                ('response_message', models.TextField()),
                ('service_interest', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_method', models.CharField(blank=True, max_length=100, null=True)),
                ('repeat_state', models.BooleanField(default=False)),
                ('next_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_next_states', to='wpmessages.chatbotstate')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='wpmessages.chatbotstate')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('choice', 'Choice'), ('number', 'Number')], max_length=50)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for choice type questions', null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='wpmessages.chatbotstate')),
            ],
        ),
    ]
