# Generated by Django 5.0.4 on 2024-06-09 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0004_alter_wpmessage_message_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbotstate',
            old_name='message',
            new_name='initial_message',
        ),
        migrations.RemoveField(
            model_name='chatbotquestion',
            name='options',
        ),
        migrations.RemoveField(
            model_name='chatbotstate',
            name='next_state',
        ),
        migrations.AddField(
            model_name='chatbotquestion',
            name='invalid_response_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChatbotOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=100)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('next_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wpmessages.chatbotstate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='wpmessages.chatbotquestion')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatbotResponse',
        ),
    ]
