# Generated by Django 5.0.4 on 2024-06-09 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0005_rename_message_chatbotstate_initial_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotoption',
            name='next_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option_next_state', to='wpmessages.chatbotstate'),
        ),
    ]
