# Generated by Django 5.0.4 on 2024-06-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0006_alter_chatbotoption_next_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotquestion',
            name='custom_field_name',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='chatbotstate',
            name='is_initial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wpmessage',
            name='custom_data',
            field=models.JSONField(default=dict),
        ),
    ]
