# Generated by Django 5.0.4 on 2024-06-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0008_remove_chatbotstate_is_initial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotstate',
            name='initial_message',
        ),
    ]
