# Generated by Django 5.0.4 on 2024-06-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0009_remove_chatbotstate_initial_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotstate',
            name='structure',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
