# Generated by Django 5.0.4 on 2024-06-10 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0010_chatbotstate_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotstate',
            name='structure',
        ),
    ]
