# Generated by Django 5.0.4 on 2024-06-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0013_remove_chatbotstate_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotquestion',
            name='state',
        ),
        migrations.DeleteModel(
            name='ChatbotOption',
        ),
        migrations.DeleteModel(
            name='ChatbotQuestion',
        ),
        migrations.DeleteModel(
            name='ChatbotState',
        ),
    ]
