# Generated by Django 5.0.4 on 2024-06-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0014_remove_chatbotquestion_state_delete_chatbotoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wpmessage',
            name='phone_id',
        ),
    ]
