# Generated by Django 5.0.4 on 2024-06-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0015_remove_wpmessage_phone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpmessage',
            name='phone_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wpmessage',
            name='state',
            field=models.CharField(blank=True, choices=[('initial', 'Initial'), ('awaiting_service', 'Awaiting Service'), ('awaiting_contact_method', 'Awaiting Contact Method'), ('completed', 'Completed')], default='initial', max_length=50, null=True),
        ),
    ]
