# Generated by Django 5.0.4 on 2024-06-14 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualadmin', '0001_initial'),
        ('wpmessages', '0016_wpmessage_phone_id_alter_wpmessage_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpmessage',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualadmin.chatbotstate'),
        ),
    ]
