# Generated by Django 5.0.4 on 2024-06-15 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0017_alter_wpmessage_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wpmessage',
            old_name='state',
            new_name='status',
        ),
    ]
