# Generated by Django 5.0.4 on 2024-06-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0018_rename_state_wpmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpmessage',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
