# Generated by Django 5.0.4 on 2024-06-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wpmessages', '0019_alter_wpmessage_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wpmessage',
            old_name='status',
            new_name='state',
        ),
    ]
