# Generated by Django 5.0.4 on 2024-05-08 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Prioridade')),
            ],
        ),
        migrations.AddField(
            model_name='suggestion',
            name='title',
            field=models.TextField(default='Título não especificado', max_length=50, verbose_name='Conteúdo'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ideabox.priority', verbose_name='Prioridade'),
        ),
    ]
