# Generated by Django 5.0.4 on 2024-05-13 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabox', '0002_priority_suggestion_title_suggestion_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Status')),
            ],
        ),
        migrations.AddField(
            model_name='suggestion',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ideabox.status', verbose_name='Status'),
        ),
    ]
