# Generated by Django 5.0.4 on 2024-06-17 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabox', '0003_status_suggestion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideabox.priority', verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideabox.status', verbose_name='Status'),
        ),
    ]
