# Generated by Django 5.0.4 on 2024-06-18 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabox', '0004_alter_suggestion_priority_alter_suggestion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='Pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ideabox.status', verbose_name='Status'),
        ),
    ]
