# Generated by Django 5.0.4 on 2024-05-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_info',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
