# Generated by Django 5.0.4 on 2024-05-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_priority_alter_client_client_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.servicetype', verbose_name='Serviços do Cliente'),
        ),
    ]
