# Generated by Django 5.0.4 on 2024-05-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_info',
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
