# Generated by Django 5.0.4 on 2024-05-14 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_client_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Cliente')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Nome do Cliente')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='Whatsapp (Telefone)')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('notes', models.TextField(blank=True, max_length=50, verbose_name='Anotações')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Cliente Associado')),
            ],
        ),
    ]
