# Generated by Django 5.0.4 on 2024-05-14 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_clientleads'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientleads',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Dia Foi Indicada'),
            preserve_default=False,
        ),
    ]
