# Generated by Django 5.0.4 on 2024-05-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_clientleads_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientleads',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Empresa da Lead'),
        ),
        migrations.AlterField(
            model_name='clientleads',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Data da Indicação'),
        ),
        migrations.AlterField(
            model_name='clientleads',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome da Lead'),
        ),
    ]
