# Generated by Django 5.0.4 on 2024-06-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_clientleads_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Aniversário do Cliente'),
        ),
    ]
