# Generated by Django 5.0.4 on 2024-06-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_client_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
